on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
    - main
    paths:
    - src/**
  workflow_dispatch:

name: Update data

jobs:
  update-data:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }} # TODO: what is this?
      GITHUB_TOKEN: ${{ secrets.WORKFLOWS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #  fetch-depth: 0
        #  token: ${{ secrets.WORKFLOWS }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      # - name: Setup pandoc
      #  uses: r-lib/actions/setup-pandoc@v2

      - name: Install R packages
        run: |
          install.packages("remotes")
          remotes::install_deps(upgrade = "always")
        shell: Rscript {0}
        cache: true

      - name: Get data
        env:
          RATO_USER: ${{ secrets.RATO_USER }}
          RATO_PWD: ${{ secrets.RATO_PWD }}
          RATO_API_CAPACITY: 1500
        run: |
          source("src/get_data.R")
        shell: Rscript {0}

      - name: Map data to Darwin Core
        env:
          RATO_USER: ${{ secrets.RATO_USER }}
          RATO_PWD: ${{ secrets.RATO_PWD }}
        run: |
          source("src/dwc_mapping.R")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.WORKFLOWS }}
          commit_prefix: "[AUTO]"
          commit_message: "Renew data"
          target_branch: automatic-update
          add_timestamp: true

      - name: Get branch name
        run: |
          git branch --show-current

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.WORKFLOWS }}
          target_branch: main
          title: "[AUTO] Update data"
          template: .github/PULL_REQUEST_TEMPLATE.md
          reviewer: PietrH
          label: automated workflow
          get_diff: false
